/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz_Grafica;

import Datos.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Datos.sesion;
import Datos.obtenerSorteo;

/**
 *
 * @author deadp
 */
public class Numeros_Manuales_Revancha extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conectar();
    
    /**
     * Creates new form Numeros_Manuales_Final
     */
    public Numeros_Manuales_Revancha() {
        initComponents();
        jTextField2.setEditable(false);
        txtPrecioRevancha.setEditable(false);
        agregarFechaActual(jTextField2);
    }
    
    private void agregarFechaActual(JTextField textField) {
        // Obtener la fecha actual
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd"); // Formato deseado para la fecha
        String fechaTexto = formato.format(fechaActual);
        
        // Establecer la fecha actual en el jTextField especificado
        textField.setText(fechaTexto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblnum1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblnum2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        lblnum3 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        lblnum4 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        lblnum5 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        lblnum6 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lblnum7 = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();
        lblresultados = new javax.swing.JTextField();
        lblnumextra = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        lblnum9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrecioRevancha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 0, 75));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Números Manuales Revancha");

        lblnum1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum1.setForeground(new java.awt.Color(255, 255, 255));
        lblnum1.setText("Número 1: ");

        jSpinner1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        lblnum2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum2.setForeground(new java.awt.Color(255, 255, 255));
        lblnum2.setText("Número 2: ");

        jSpinner2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        lblnum3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum3.setForeground(new java.awt.Color(255, 255, 255));
        lblnum3.setText("Número 3: ");

        jSpinner3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        lblnum4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum4.setForeground(new java.awt.Color(255, 255, 255));
        lblnum4.setText("Número 4: ");

        jSpinner4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        lblnum5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum5.setForeground(new java.awt.Color(255, 255, 255));
        lblnum5.setText("Número 5: ");

        jSpinner5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        lblnum6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum6.setForeground(new java.awt.Color(255, 255, 255));
        lblnum6.setText("Número 6: ");

        jSpinner6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblnum7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum7.setForeground(new java.awt.Color(255, 255, 255));
        lblnum7.setText("Números Seleccionados:");

        btnaceptar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar.png"))); // NOI18N
        btnaceptar.setText("Validar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        lblresultados.setBackground(new java.awt.Color(132, 84, 199));
        lblresultados.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblresultados.setForeground(new java.awt.Color(255, 255, 255));
        lblresultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblresultadosActionPerformed(evt);
            }
        });

        lblnumextra.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnumextra.setForeground(new java.awt.Color(255, 255, 255));
        lblnumextra.setText("Número Extra (Segunda Oportunidad): ");

        jSpinner7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(1, 1, 56, 1));

        lblnum9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblnum9.setForeground(new java.awt.Color(255, 255, 255));
        lblnum9.setText("Fecha:");

        jTextField2.setBackground(new java.awt.Color(132, 84, 199));
        jTextField2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio:");

        txtPrecioRevancha.setBackground(new java.awt.Color(132, 84, 199));
        txtPrecioRevancha.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        txtPrecioRevancha.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioRevancha.setText("$60.00");
        txtPrecioRevancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioRevanchaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblnum9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblnumextra)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblnum7)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblnum2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblnum1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblnum3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblnum6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblnum5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblnum4)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSpinner4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(txtPrecioRevancha)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnaceptar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnum9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecioRevancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblnum4)
                        .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblnum1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnum2)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnum5)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnum3)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnum6)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumextra)
                    .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnum7)
                    .addComponent(lblresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnaceptar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
         try{
          
          int idUsuario = sesion.getUserId();
          int idSorteo = obtenerSorteo.getSorteoId();
          
           PreparedStatement ps = cn.prepareStatement("INSERT INTO revancha(num1,num2,num3,num4,num5,num6,adicional1,fechaSorteo,usuario,tipo_sorteo) VALUES (?,?,?,?,?,?,?,?,?,?)");
           int num1 = (int) jSpinner1.getValue();
           ps.setInt(1, num1);
           int num2 = (int) jSpinner2.getValue();
           ps.setInt(2, num2);
           int num3 = (int) jSpinner3.getValue();
           ps.setInt(3, num3);
           int num4 = (int) jSpinner4.getValue();
           ps.setInt(4, num4);
           int num5 = (int) jSpinner5.getValue();
           ps.setInt(5, num5);
           int num6 = (int) jSpinner6.getValue();
           ps.setInt(6, num6);   
           int num7 = (int) jSpinner7.getValue();
           ps.setInt(7, num7); 
           String fecha = jTextField2.getText();
           ps.setString(8, fecha);
           ps.setInt(9, idUsuario);
           ps.setInt(10, idSorteo);
           String resultados = num1 + "," + num2 + "," + num3 + "," + num4 + "," + num5 + "," + num6 + "," + num7;
           lblresultados.setText(resultados);
           ps.executeUpdate();
           JOptionPane.showMessageDialog(null, "Numeros Guardados Corectamente");
       }catch(SQLException ex){}
       dispose();
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tipos_Juego().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void lblresultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblresultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblresultadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generacion_Numeros_Melate().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtPrecioRevanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioRevanchaActionPerformed
        txtPrecioRevancha.setEditable(false);
    }//GEN-LAST:event_txtPrecioRevanchaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numeros_Manuales_Revancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numeros_Manuales_Revancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numeros_Manuales_Revancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numeros_Manuales_Revancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numeros_Manuales_Revancha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblnum1;
    private javax.swing.JLabel lblnum2;
    private javax.swing.JLabel lblnum3;
    private javax.swing.JLabel lblnum4;
    private javax.swing.JLabel lblnum5;
    private javax.swing.JLabel lblnum6;
    private javax.swing.JLabel lblnum7;
    private javax.swing.JLabel lblnum9;
    private javax.swing.JLabel lblnumextra;
    private javax.swing.JTextField lblresultados;
    private javax.swing.JTextField txtPrecioRevancha;
    // End of variables declaration//GEN-END:variables
}
